services:
  - elasticsearch
language: ruby
script: 'bundle exec rake ci'
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode
notifications:
  irc: "irc.freenode.org#rom-rb"
